#ifndef GuideDef_h__
#define GuideDef_h__

//引导结点类型 
enum GUIDE_NODE_TYPE
{
	GUIDE_NODE_GUIDE = 1, //引导类型
	GUIDE_NODE_CHAT,	  //对话类型
	GUIDE_NODE_FIGHT,	  //触发战斗类型
	GUIDE_NODE_EMPTY,	  //空引导，不执行任何操作，直接跳转到下一引导	
	GUIDE_NODE_ANIMATION  //动画引导类型
};

//引导结点是否为关键结点
enum GUIDE_NODE_KEY_NODE
{
	GUIDE_NODE_KEY = 0,
	GUIDE_NODE_NOT_KEY
};

//引导结点是否为强制
enum GUIDE_NODE_FORCE_NODE
{
	GUIDE_NODE_FORCE = 1,
	GUIDE_NODE_NOT_FORCE
};

//引导结点在引导链上的位置
enum GUIDE_NODE_CHAIN_TYPE
{
	GUIDE_NODE_CHAIN_NORMAL = 0,					//普通结点
	GUIDE_NODE_CHAIN_HEAD,							//头结点
	GUIDE_NODE_CHAIN_TAIL							//尾结点
};

//引导触发类型
enum GUIDE_NODE_TRIGGER_TYPE
{
	GUIDE_NODE_TRIGGER_FIGHT_START = 1,				//战斗开始，人物入场后
	GUIDE_NODE_TRIGGER_FIGHT_ROUND,					//战斗回合开始
	GUIDE_NODE_TRIGGER_FIGHT_END,					//战斗结束
	GUIDE_NODE_TRIGGER_PRIOR_DONE,					//上一引导结束
	GUIDE_NODE_TRIGGER_LEVEL,						//等级引导
	GUIDE_NODE_TRIGGER_FIGHT_BEFORE,				//战斗开始，人物入场前
	GUIDE_NODE_TRIGGER_FIGHT_ROUND_END,				//战斗回合结束
	GUIDE_NODE_TRIGGER_ROUND_ENEMY_BEFORE			//战斗敌方出手前
};

//引导触发的界面
enum GUIDE_NODE_INTERFACE
{
	GUIDE_INTERFACE_MAIN = 10001,					//主界面
	GUIDE_INTERFACE_HERO = 10002,					//阵容界面(角色界面)
	GUIDE_INTERFACE_EQUIP_INFO = 10003,				//装备详情界面
	GUIDE_INTERFACE_BARRIER_FORMATION = 10004,		//战前阵形界面
	GUIDE_INTERFACE_MAIN_HERO_SKILL = 10005,		//主角技能界面
	GUIDE_INTERFACE_HERO_BAG = 10006,				//英雄背包界面
//	GUIDE_INTERFACE_TRANNING = 10007,				//训练界面
	GUIDE_INTERFACE_TASK = 10008,					//任务界面
	GUIDE_INTERFACE_SHOP_1 = 10009,					//商城正面
	GUIDE_INTERFACE_SHOP_DONE = 10010,				//抽卡完成界面

	GUIDE_INTERFACE_CHAPTER = 10011,				//章节界面
	GUIDE_INTERFACE_STAGE = 10012,					//关卡界面
//	GUIDE_INTERFACE_STAGE_STAR_REWARD = 10013,		//星级奖励界面
//	GUIDE_INTERFACE_EXPERIENCE = 10014,				//阅历界面
	GUIDE_INTERFACE_ACTIVITY = 10015,				//活动关卡界面
	GUIDE_INTERFACE_MAZE = 10016,					//迷宫界面
	GUIDE_INTERFACE_ARENA = 10017,					//竞技场界面
	GUIDE_INTERFACE_STAR_PLATE = 10018,				//星盘界面
	GUIDE_INTERFACE_PRACTICE = 10019,				//试练主界面
	GUIDE_INTERFACE_CLIMB_TOWER = 10020,			//爬塔界面

	GUIDE_INTERFACE_LIFE_PRACTICE = 10021,			//生存试练
	GUIDE_INTERFACE_LOVE = 10022,					//情缘界面
	GUIDE_INTERFACE_LOVE_REWARD = 10023,			//情缘奖励界面
	GUIDE_INTERFACE_FIGHT = 10024,					//战斗场景
	GUIDE_INTERFACE_REFINE = 10025,					//炼化炉界面
// 	GUIDE_INTERFACE_STAR_SPRITE = 10026,			//星灵界面(no)
// 	GUIDE_INTERFACE_STAR_SPRITE_PROPERTITY = 10027,	//星灵属性界面(no)
	GUIDE_INTERFACE_LOGIN = 10028,					//登录界面
	GUIDE_INTERFACE_STAR_PLATE_INFO = 10029,		//星盘二级界面,星盘详情
	GUIDE_INTERFACE_ROB = 10030,					//掠夺界面

	GUIDE_INTERFACE_ROB_SELECT_ENEMY = 10031,		//掠夺选择对手界面
	GUIDE_INTERFACE_ROB_REWARD = 10032,				//掠夺奖励界面
//	GUIDE_INTERFACE_STAGE_RESULT = 10033,			//关卡结算界面(no)
	GUIDE_INTERFACE_LEVEL_UP = 10034,				//角色升级界面
//	GUIDE_INTERFACE_ADVANCE_DIALOG = 10035,			//觉醒弹窗(no)
	GUIDE_INTERFACE_CARD_SHOW = 10036,				//卡牌展示界面
	GUIDE_INTERFACE_BREAK_SUCCESS = 10037,			//英雄觉醒突破成功界面
	GUIDE_INTERFACE_HERO_LEVEL_UP = 10038,			//英雄升级
	GUIDE_INTERFACE_LOVE_FUNC = 10039,				//情缘(游玩 猜拳)
	GUIDE_INTERFACE_LOVE_GIFT = 10040,				//情缘送礼界面
	GUIDE_INTERFACE_ARENA_SHOP = 10041,				//竞技场商城
	GUIDE_INTERFACE_TRAIL_SHOP = 10042,				//试炼商城
	GUIDE_INTERFACE_EQUIP_PUT_ON = 10043,			//装备穿戴
	GUIDE_INTERFACE_TRAIL_SELECT_OP = 10044,		//试炼选择对手
	GUIDE_INTERFACE_TRAIL_FORMATION = 10045,		//试炼阵型
	GUIDE_INTERFACE_XINGXIU = 10046,				//星宿
	GUIDE_INTERFACE_FATE = 10047,					//主角缘分界面
	GUIDE_INTERFACE_FORMATION = 10048,				//主界面阵型界面
	GUIDE_INTERFACE_PVP_RANK = 10049,				//竞技场排名界面
	GUIDE_INTERFACE_MARVELLOUSACTIVE = 10050,		//精彩活动
	GUIDE_INTERFACE_TACTICS = 10051,				//阵形养成
	GUIDE_INTERFACE_TACTICS_SELECT = 10052,			//阵形养成道具选择
	GUIDE_INTERFACE_ROB_COMPOSE = 10053,			//掠夺合成界面
	GUIDE_INTERFACE_COMMON_REWARD = 10054,			//通用奖励对话框
	GUIDE_INTERFACE_ARTIFACT = 10055,				//神器界面
	GUIDE_INTERFACE_LOVE_ADD = 10056,				//情缘加点界面
	GUIDE_INTERFACE_STAR_PLATE_HERO_INFO = 10057,	//星盘加成详情界面
	GUIDE_INTERFACE_STAR_PLATE_BUY = 10058,			//星盘购买界面
	GUIDE_INTERFACE_ITEM_SHOP = 10059,				//集市装备抽取商店
	GUIDE_INTERFACE_ITEM_SHOP_DONE = 10060,			//装备抽取完成界面
	GUIDE_INTERFACE_GROUP_APPLY = 10061,			//帮派申请界面
	GUIDE_INTERFACE_GROUP_MAIN = 10062,				//帮派主界面
	GUIDE_INERFACE_FRIEND = 10063,					//好友界面
	GUIDE_INTERFACE_STAR_UP = 10064,				//升星界面
	GUIDE_INTERFACE_ARENA_SUB_PAGE = 10065,			//竞技场分页
	GUIDE_INTERFACE_HERO_FATE_ACTIVE = 10066		//缘分提升/激活界面
};

//引导NPC显示方位
enum GUIDE_NODE_NPC_DIR
{
	GUIDE_NODE_NPC_LEFT = 1,
	GUIDE_NODE_NPC_RIGHT
};

//引导中心通知引导事件
enum GUIDE_NOTIFY_FLAG
{
	GUIDE_NOTIFY_START,
	GUIDE_NOTIFY_NEXT,
	GUIDE_NOTIFY_END
};

//引导结点滚屏类型
enum GUIDE_NODE_SCROLL_TYPE
{
	GUIDE_NODE_SCROLL_MIDDLE = 0,
	GUIDE_NODE_SCROLL_LEFT = 1,
	GUIDE_NODE_SCROLL_RIGHT
};

enum GUIDE_NODE_JUMP_MAIN
{
	GUIDE_NODE_JUMP = 0,
	GUIDE_NODE_NOT_JUMP = 1
};

enum FUNCTION_TYPE
{
	FUNCTION_SPEED_X2 = 10001,			//2倍速度
	FUNCTION_SPEED_X3 = 10002,			//3倍速度
	FUNCTION_PVE = 10003,				//冒险
	FUNCTION_SHOP = 10004,				//商城
	FUNCTION_MAZE = 10005,				//迷宫
	FUNCTION_TOWER = 10006,				//千层塔
	FUNCTION_ROB = 10007,				//掠夺
	FUNCTION_LOVE = 10008,				//情缘
//	FUNCTION_STAR_SPRITE = 10009,		//星灵
	FUNCTION_PVP = 10010,				//竞技场
	FUNCTION_EQUIP_STRENGTHEN = 10011,	//装备强化(no)
	FUNCTION_EQUIP_ADVANCE = 10012,		//装备进阶(no)
	FUNCTION_EQUIP_WASH = 10013,		//装备洗练(no)
	FUNCTION_HERO_ADVANCE = 10014,		//英雄进阶
//	FUNCTION_TRANNING = 10015,			//训练
	FUNCTION_FACTION = 10016,			//帮派(no)
	FUNCTION_PVE_EVENT = 10017,			//活动副本
//	FUNCTION_EXPERIENCE = 10018,		//阅历
	FUNCTION_SWEEP = 10019,				//扫荡
	FUNCTION_TALENT = 10020,			//天赋
// 	FUNCTION_FORMATION_3 = 10021,		//阵位3开放
// 	FUNCTION_FORMATION_4 = 10022,		//阵位4开放
// 	FUNCTION_FORMATION_5 = 10023,		//阵位5开放
	FUNCTION_TASK = 10024,				//任务
	FUNCTION_TRAIL = 10025,				//试炼
	FUNCTION_STAR_PLATE = 10026,		//星盘
	FUNCTION_STAR_SU = 10027,			//星宿
	FUNCTION_MAIN_HERO_FATE = 10028,	//主角缘分
	FUNCTION_AUTO_FIGHT = 10029,		//自动战斗
	FUNCTION_FIGHT_ESCAPE = 10030,		//战斗逃跑
	FUNCTION_TOWER_TRAIL = 10031,		//试练塔
	FUNCTION_BOSS = 10032,				//世界boss
	FUNCTION_REFINE = 10033,			//炼化炉
	FUNCTION_TACTICS = 10034,			//阵法
	FUNCTION_ACHIEVEMENT_TASK = 10035,	//成就任务
	FUNCTION_DAILY_TASK = 10036,		//日常任务
	FUNCTION_SHENQI = 10038,            //神器
	FUNCTION_EQUIP_CL = 10039,			//装备淬炼/淬炼商店
	FUNCTION_SWEEP_10 = 10040,			//扫荡10次
	FUNCTION_HORSE_BOOK = 10041,		//马书强化
	FUNCTION_RANK_TOP = 10042			//排行榜
};

#endif //GuideDef_h__