#ifndef MainTaskDef_h__
#define MainTaskDef_h__

enum TASK_STATE
{
	TASK_STATE_NONE,	//任务未激活、未完成
	TASK_STATE_ACTIVE,	//任务已激活
	TASK_STATE_DONE		//任务已完成
};

enum TASK_TYPE
{
	TASK_ALL,					//全部任务
	TASK_TYPE_ACHIEVEMENT,		//成就任务
	TASK_TYPE_DAILY				//日常任务
};

enum TASK_COND_TYPE
{
	TASK_COND_LEVEL = 1,
	TASK_COND_FIRST_CLEAR_STAGE = 2,
	TASK_COND_HERO_COUNT = 3,
	TASK_COND_AWAKE_LEVEL = 4,
	TASK_COND_STRENGTH_LEVEL = 5,
	TASK_COND_ADVANCED_LEVEL = 6,
	TASK_COND_TREASURE_COUNT = 7,
	TASK_COND_STARSPRITE_COUNT = 8,
	TASK_COND_STARSPRITE_STAR_COUNT = 9,
	TASK_COND_ARENA_RANK = 10,
	TASK_COND_FRIEND_COUNT = 11,
	TASK_COND_MAIN_FATE = 12,
	TASK_COND_TOWER_FLOOR_COUNT = 13,
	TASK_COND_CLEAR_STAGE_COUNT = 14,
	TASK_COND_ROB_COUNT = 15,
	TASK_COND_ARENA_COUNT = 16,
	TASK_COND_GIVE_POWER_COUNT = 17,
	TASK_COND_TOWER_COUNT = 18,
	TASK_COND_TRIAL_COUNT = 19,
	TASK_COND_MAZE_COUNT = 20,
	TASK_COND_GIVE_GIFT_COUNT = 21,
	TASK_COND_GET_TIMER_POWER = 22,
	TASK_COND_EQUIP_WASH_COUNT = 23,
	TASK_COND_VIP = 24,
	TASK_COND_TAKE_CARD = 25,
};

enum TASK_JUMP_SCENE_TYPE
{
	TASK_JUMP_SCENE_CHAPTER = 1,
	TASK_JUMP_SCENE_HERO,
	TASK_JUMP_SCENE_PVP,
	TASK_JUMP_SCENE_LOVE,
	TASK_JUMP_SCENE_TOWER,
	TASK_JUMP_SCENE_ROB,
	TASK_JUMP_SCENE_FRIEND,
	TASK_JUMP_SCENE_MAZE,
	TASK_JUMP_SCENE_SHOP,
	TASK_JUMP_SCENE_FORMATION2, //阵法
	TASK_JUMP_SCENE_STAR_SU,
	TASK_JUMP_SCENE_GET_COIN, //祈福弹窗
	TASK_JUMP_SCENE_BOSS,
	TASK_JUMP_SCENE_STARS_CAMP,
	TASK_JUMP_SCENE_ARTIFACT,
	TASK_JUMP_SCENE_GROUP,		//帮派
	TASK_JUMP_SCENE_GET_POWER,	//购买体力
	TASK_JUMP_SCENE_ACTIVITY	//每日挑战
};

enum TASK_EVENT_TYPE
{
	TASK_EVENT_INIT = 5236,		//初始化
	TASK_EVENT_UPDATE,			//更新
	TASK_EVENT_RECEIVE			//领取
};


#endif //MainTaskDef_h__